name: Count README Stats

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  count_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Read README and Count
      id: readme_stats
      run: |
        README_CONTENT=$(cat README.md)  # Update the filename if your README has a different name
        WORD_COUNT=$(echo "$README_CONTENT" | wc -w)
        LINE_COUNT=$(echo "$README_CONTENT" | wc -l)
        # You can add more counts or processing as needed
        echo "::set-output name=word_count::$WORD_COUNT"
        echo "::set-output name=line_count::$LINE_COUNT"

    - name: Display Counts
      run: |
        echo "Word Count: ${{ steps.readme_stats.outputs.word_count }}"
        echo "Line Count: ${{ steps.readme_stats.outputs.line_count }}"
