# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Read README and Count
        id: readme_stats
        run: |
          README_CONTENT=$(cat README.md)
          # Extract all lines of the table
          TABLE_LINES=$(echo "$README_CONTENT" | sed -n '/|/p')
          LINE_COUNT=$(echo "$TABLE_LINES"|wc -l)
          ACTIVE_COUNT=$(echo "$TABLE_LINES"|awk -F"|" '{print $2}'|grep "Yes"|wc -l)
          INACTIVE_COUNT=$(echo "$TABLE_LINES"|awk -F"|" '{print $2}'|grep "No"|wc -l)
          EDGE_CASE_COUNT=$(echo "$TABLE_LINES"|awk -F"|" '{print $2}'|grep "Edge Case"|wc -l)
          echo "::set-output name=line_count::$LINE_COUNT"
          echo "::set-output name=active_count::$ACTIVE_COUNT"
          echo "::set-output name=inactive_count::$INACTIVE_COUNT"
          echo "::set-output name=edge_case_count::$EDGE_CASE_COUNT"

      -  name: Display Counts
         run: |
           echo "Total Takeovers Count: ${{ steps.readme_stats.outputs.line_count }}"
           echo "Active Takeovers Count: ${{ steps.readme_stats.outputs.active_count }}"
           echo "Inactive Takeovers Count: ${{ steps.readme_stats.outputs.inactive_count }}"
           echo "Edge Case Takeovers Count: ${{ steps.readme_stats.outputs.edge_case_count }}"
